# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.resize(400, 358)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConfigDialog.setWindowIcon(icon)
        self.checkBoxChamps = QtWidgets.QCheckBox(ConfigDialog)
        self.checkBoxChamps.setGeometry(QtCore.QRect(50, 20, 111, 17))
        self.checkBoxChamps.setObjectName("checkBoxChamps")
        self.checkBoxSymbio = QtWidgets.QCheckBox(ConfigDialog)
        self.checkBoxSymbio.setGeometry(QtCore.QRect(50, 50, 111, 17))
        self.checkBoxSymbio.setObjectName("checkBoxSymbio")
        self.btnConfirm = QtWidgets.QPushButton(ConfigDialog)
        self.btnConfirm.setGeometry(QtCore.QRect(250, 20, 101, 41))
        self.btnConfirm.setStyleSheet("font: bold 11pt \"MS Shell Dlg 2\"; color : red")
        self.btnConfirm.setObjectName("btnConfirm")
        self.label = QtWidgets.QLabel(ConfigDialog)
        self.label.setGeometry(QtCore.QRect(30, 140, 321, 81))
        self.label.setStyleSheet("font: bold 11pt \"Garamond\"; color : red")
        self.label.setObjectName("label")
        self.lineLayer = QtWidgets.QLineEdit(ConfigDialog)
        self.lineLayer.setGeometry(QtCore.QRect(140, 100, 231, 20))
        self.lineLayer.setStyleSheet("font: 12pt \"Garamond\";")
        self.lineLayer.setObjectName("lineLayer")
        self.label_2 = QtWidgets.QLabel(ConfigDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 101, 21))
        self.label_2.setObjectName("label_2")
        self.textEditChamps = QtWidgets.QTextEdit(ConfigDialog)
        self.textEditChamps.setGeometry(QtCore.QRect(20, 230, 351, 111))
        self.textEditChamps.setObjectName("textEditChamps")

        self.retranslateUi(ConfigDialog)
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)

    def retranslateUi(self, ConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigDialog.setWindowTitle(_translate("ConfigDialog", "Configuration"))
        self.checkBoxChamps.setToolTip(_translate("ConfigDialog", "<html><head/><body><p>champs nécessaires au plugin</p></body></html>"))
        self.checkBoxChamps.setText(_translate("ConfigDialog", "Créer les champs"))
        self.checkBoxSymbio.setToolTip(_translate("ConfigDialog", "<html><head/><body><p>Légende et couleurs</p></body></html>"))
        self.checkBoxSymbio.setText(_translate("ConfigDialog", "Créer symbiologie"))
        self.btnConfirm.setToolTip(_translate("ConfigDialog", "<html><head/><body><p>Validation</p></body></html>"))
        self.btnConfirm.setText(_translate("ConfigDialog", "Confirmer"))
        self.label.setText(_translate("ConfigDialog", "<html><head/><body><p align=\"center\">Vous devez cocher les deux cases </p><p align=\"center\">puis <span style=\" font-size:14pt;\">Confirmer</span>. </p><p align=\"center\">Assurer vous d\'avoir sauvegardez votre table</p></body></html>"))
        self.label_2.setText(_translate("ConfigDialog", "Couche sélectionnée :"))
        self.textEditChamps.setToolTip(_translate("ConfigDialog", "<html><head/><body><p>Liste des champs qui vont être créés</p></body></html>"))
